### ISSUE TITLE
Failing to load the file: "./styles/leaflet-lumo-theme.css"

### ISSUE THREAD

**Issue by syampillai** [Gubancs/leaflet4vaadin#3]
I tested it with Vaadin 14.1.18 and it is failing to load the file: "./styles/leaflet-lumo-theme.css".

I think, In add-ons, this file should be put under the folder:
src/main/resources/META-INF/resources/frontend/

**Comment by Gubancs** [comment]
Hi, 

Thank you for your reporting. Currently  I’m on holiday but maybe after tomorrow I will fix this issue.

Thanks in advance!

**Comment by ugurdoksan** [comment]
Not working on Vaadin Flow V15 with **0.2.3-beta**

**Comment by Gubancs** [comment]
> Not working on Vaadin Flow V15 with **leaflet4vaadin 0.2.3-beta**
Hi, have you any new error message in your log file?

**Comment by ugurdoksan** [comment]
@Gubancs There is no error message neither in Tomcat nor in Chrome console. The basic map can not display in empty View.

You can try your DemoView with Vaadin V15.

**Comment by Gubancs** [comment]
@ugurdoksan interesting because I tested the 0.2.3-beta version using the https://vaadin.com/start/latest with Spring boot technology stack and it worked for me.
