### ISSUE TITLE
Add Overlays Option

### ISSUE THREAD

**Issue by jimbok8** [Gubancs/leaflet4vaadin#6]
Thanks for your code - much appreciated.
Please could you add the feature to be able to add overlay tilelayers on top of base maps?
I would like to add an overlay like:
"https://{s}.tiles.openrailwaymap.org/standard/{z}/{x}/{y}.png"
In leaflet it is done like this:

    var baseLayers = {
    "Mapbox": mapbox,
    "OpenStreetMap": osm
    };
    var overlays = {
    "Railways": railwaysLayer
    };
    L.control.layers(baseLayers, overlays).addTo(map);

Or have I missed something and this is already possible?
Thanks.
Jim

**Comment by Gubancs** [comment]
Hi,

The layer control added to the map by default, so you can add multiple base layers to the map using TileLayers.
example: https://leaflet4vaadin.herokuapp.com/layers/baselayers

`
		final MapOptions options = new DefaultMapOptions();
		options.setCenter(new LatLng(47.070121823, 19.204101562500004));
		options.setZoom(7);
		final LeafletMap leafletMap = new LeafletMap(options);
		leafletMap.setBaseUrl("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png");

		TileLayer wikimedia = new TileLayer("https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png");
		wikimedia.setAttribution("Wikimedia Maps");
		wikimedia.setName("Wikimedia Maps");
		wikimedia.addTo(leafletMap);
`
But in the future, I am going to improve the layer control because it could be better.

**Comment by jimbok8** [comment]
What I am trying to achieve is shown at the bottom of the following picture. In this display there are multiple 'baselayers', and also multiple 'overlays' which I have circled with a red ellipse. The overlays are also tile layers and, from what I can remember, have to be installed when the layer control is first added.

Is this possible in Leaflet4Vaadin?

![Leaflet4Vaadin](https://user-images.githubusercontent.com/9551560/82571529-fbbcef00-9b7a-11ea-8db7-a2bef5b79af6.png)

**Comment by Gubancs** [comment]
Hi @jimbok8,
I am very sorry for the inconvenience but currently it is not possible because there is a small bug in the layer handling. 
I will fix this issue in the next release version.

Thanks for advance.
